{
 "title": "DNS-SSL",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "targets",
    "query": "label_values(probe_success,instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "$targets UP/DOWN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "targets" },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$targets\"}-time()"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$targets\"})"
    }
   ]
  }
 ]
}