{
 "title": "Aerospike-nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Exporter Status",
   "type": "singlestat",
   "description": "Exporter status",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(up{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$service|$^\"})"
    }
   ]
  },
  {
   "title": "Server Node",
   "type": "singlestat",
   "description": "Aerospike server status",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "description": "Alert count",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ALERTS{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "singlestat",
   "description": "Client connections count",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "All Objects",
   "type": "singlestat",
   "description": "Total objects count",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "All Tombstones",
   "type": "singlestat",
   "description": "Total tombstones count",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Mem.",
   "type": "singlestat",
   "description": "Total namespace memory size",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_size{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used Mem.",
   "type": "singlestat",
   "description": "Total namespace memory used in bytes",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Free Mem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(aerospike_namespace_memory_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "singlestat",
   "description": "Total device size in bytes",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_total_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "singlestat",
   "description": "Total device usage in bytes",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(aerospike_namespace_device_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Latency: Reads / sec",
   "type": "graph",
   "description": "Reads per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_latencies_read_ms_bucket{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}ms"
    },
    {
     "expr": "avg(aerospike_latencies_read_ms_count{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Latency: Writes / sec",
   "type": "graph",
   "description": "Writes per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_latencies_write_ms_bucket{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}ms"
    },
    {
     "expr": "avg(aerospike_latencies_write_ms_count{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Client connections, fabric connections and heartbeat connections",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Client Connections"
    },
    {
     "expr": "aerospike_node_stats_fabric_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Fabric Connections"
    },
    {
     "expr": "aerospike_node_stats_heartbeat_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Heartbeat Connections"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "graph",
   "description": "Master objects, prole objects and tombstones",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_namespace_master_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Master"
    },
    {
     "expr": "aerospike_namespace_prole_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Prole"
    },
    {
     "expr": "aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Tombstones"
    }
   ]
  }
 ]
}