{
 "title": "Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
   },
   { "name": "tags", "label": "Tags" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "text",
   "description": "Cluster name",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "content": "<center><h2>$cluster</h1></center>",
   "targets": [
    {
     "expr": "min(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Aerospike Version",
   "type": "singlestat",
   "description": "Build version",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "description": "Cluster size",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "description": "Alert count",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Stop Writes",
   "type": "singlestat",
   "description": "Namespace stop_writes flag",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_stop_writes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Clock Skew Stop Writes",
   "type": "singlestat",
   "description": "Namespace clock_skew_stop_writes flag",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_clock_skew_stop_writes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Migrations Remaining",
   "type": "singlestat",
   "description": "Total migration partitions remaining (transmit + receive)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) + sum(aerospike_namespace_migrate_tx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  { "title": "Node Statstics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Client Connections",
   "type": "graph",
   "description": "Client connection count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "graph",
   "description": "Cluster size (cluster_size)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_cluster_size{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Allocated Heap Memory",
   "type": "graph",
   "description": "Heap allocated memory (heap_allocated_kbytes)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_heap_allocated_kbytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mapped Memory",
   "type": "graph",
   "description": "Heap mapped memory (heap_mapped_kbytes)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_heap_mapped_kbytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Heap Efficiency",
   "type": "graph",
   "description": "Heap efficiency % (heap_efficiency_pct)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_heap_efficiency_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Throughput (Batch)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "content": "&nbsp;\n\n### For namespace specific throughput please see the [Namespace View dashboard](/d/zGcUKcDZz/namespace-view)."
  },
  {
   "title": "Batch Reads (TPS)",
   "type": "graph",
   "description": "Batch Index TPS shows per-second average rate of increase in\n\n1. Total = batch_index_complete\n2. Successful = batch_index_complete - (batch_index_timeout + batch_index_error)\n3. Timeout = batch_index_timeout\n4. Error = batch_index_error",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_node_stats_batch_index_complete{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}: Total"
    },
    {
     "expr": "rate(aerospike_node_stats_batch_index_complete{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) - (rate(aerospike_node_stats_batch_index_timeout{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_node_stats_batch_index_error{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "{{service}}: Successful"
    },
    {
     "expr": "rate(aerospike_node_stats_batch_index_timeout{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}: Timeout"
    },
    {
     "expr": "rate(aerospike_node_stats_batch_index_error{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}: Error"
    }
   ]
  }
 ]
}